"use client";
import { useState } from "react";
import { OWNERS, KINDS, summarize, budgetSummary, money, sumSafe, type LedgerData, type Owner } from "@/lib/domain";
import BudgetEditor from "./BudgetEditor";
export default function Dashboard({ data, month, onDirty, onSaved, onTransactions, annual, setAnnual }: { data: LedgerData; month: string; onDirty: (scope: string, dirty: boolean) => void; onSaved: () => Promise<void>; onTransactions: (owner?: Owner, filter?: string) => void; annual: boolean; setAnnual: (value: boolean) => void }) {
  const [perspective, setPerspective] = useState<"allocation" | "consumption">("allocation");
  const total = summarize(data.transactions), planned = budgetSummary(data.budgets, data.categories);
  const amounts = [
    { title:"실제 수입", value:total.income, sub:`예정 수입 ${money(total.plannedIncome)}`, filter:"income" },
    { title:"소비지출", value:total.expense, sub:"확정 소비지출 − 연결된 환불", filter:"expense" },
    { title:"저축·투자 / 원금상환", value:total.allocation, sub:"소비와 구분한 자금배분", filter:"allocation" },
    { title:"자금배분 후 여유자금", value:total.remaining, sub:"계산상 금액 · 실제 계좌잔액과 구분", filter:"balance" },
    { title:"미확정 예정 지출·배분", value:total.plannedOut, sub:"실제 실적에 포함되지 않음", filter:"plannedOut" },
  ];
  const categoryRows = data.categories.filter(c => ["income","expense","saving","loan_principal"].includes(c.kind)).map(c => {
    const plan = data.budgets.filter(b=>b.category_id===c.id).reduce((a,b)=>sumSafe(a,b.amount),0);
    const actual = data.transactions.filter(t=>t.status==="confirmed"&&t.category_id===c.id).reduce((a,t)=>sumSafe(a,t.kind==="refund"?-t.amount:t.amount),0);
    return {...c,plan,actual};
  }).filter(c=>c.plan||c.actual);
  const expenseRows=categoryRows.filter(c=>c.kind==="expense"&&c.actual>0), highest=Math.max(1,...expenseRows.map(c=>c.actual));
  return <>
    <div className="metric-grid">{amounts.map((m,i)=><button className={`metric ${i===3?"accent-metric":""}`} key={m.title} onClick={()=>onTransactions(undefined,m.filter)}><span>{m.title}</span><strong>{money(m.value)}</strong><small>{m.sub}</small></button>)}</div>
    <div className="view-toolbar"><div className="segmented"><button aria-pressed={!annual} className={!annual?"active":""} onClick={()=>setAnnual(false)}>월간</button><button aria-pressed={annual} className={annual?"active":""} onClick={()=>setAnnual(true)}>연간</button></div><div className="segmented"><button aria-pressed={perspective==="consumption"} className={perspective==="consumption"?"active":""} onClick={()=>setPerspective("consumption")}>소비 관점</button><button aria-pressed={perspective==="allocation"} className={perspective==="allocation"?"active":""} onClick={()=>setPerspective("allocation")}>자금배분 관점</button></div><span className="muted">{perspective==="consumption"?`수입 − 소비 = ${money(total.consumptionRemaining)}`:`수입 − 소비 − 저축·투자·원금상환 = ${money(total.remaining)}`}</span></div>
    {annual?<section className="panel"><div className="section-heading"><div><h2>{month.slice(0,4)}년 월별 비교</h2><p>계획과 실제 모두 소비·저축·투자·원금상환을 포함합니다. 내부이체·카드정산·대출금 수령은 제외합니다.</p></div></div>{!data.annual_transactions?<p role="status">연간 자료를 불러오는 중…</p>:<div className="table-scroll"><table className="report-table"><thead><tr>{["월","계획수입","계획지출·배분","계획여유자금","실제수입","실제지출·배분","실제여유자금","계획 메모"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{Array.from({length:12},(_,i)=>{
      const m=`${month.slice(0,4)}-${String(i+1).padStart(2,"0")}`, bs=(data.annual_budgets??[]).filter(b=>b.month===m), plan=budgetSummary(bs,data.categories), actual=summarize(data.annual_transactions!.filter(t=>t.date.startsWith(m)));
      return <tr key={m}><th>{i+1}월</th><td className="numeric">{money(plan.income)}</td><td className="numeric">{money(sumSafe(plan.expense,plan.allocation))}</td><td className="numeric">{money(plan.remaining)}</td><td className="numeric">{money(actual.income)}</td><td className="numeric">{money(sumSafe(actual.expense,actual.allocation))}</td><td className="numeric">{money(actual.remaining)}</td><td>{bs.map(b=>b.label).filter(Boolean).join(" · ")||"—"}</td></tr>;
    })}</tbody></table></div>}</section>:<>
    <section className="panel"><div className="section-heading"><div><h2>부부 · 가계 전체 비교</h2><p>같은 거래원장에서 귀속별로 집계합니다. 로그인 사용자와 거래 귀속은 별개입니다.</p></div><button onClick={()=>onTransactions("기타")}>기타 내역 조회·입력</button></div><div className="table-scroll"><table className="report-table"><thead><tr><th>귀속</th><th className="numeric">실제 수입</th><th className="numeric">소비지출</th><th className="numeric">저축·투자·원금상환</th><th className="numeric">{perspective==="consumption"?"소비 후 여유자금":"배분 후 여유자금"}</th><th className="numeric">미확정 지출·배분</th></tr></thead><tbody>{[...OWNERS,"전체" as const].map(owner=>{
      const s=summarize(data.transactions,owner==="전체"?undefined:owner);
      return <tr key={owner} className={owner==="전체"?"total-row":""}><th><button className="text-button" onClick={()=>onTransactions(owner==="전체"?undefined:owner)}>{owner}</button></th>{[s.income,s.expense,s.allocation,perspective==="consumption"?s.consumptionRemaining:s.remaining,s.plannedOut].map((v,i)=><td className="numeric" key={i}><button className="number-link" onClick={()=>onTransactions(owner==="전체"?undefined:owner,["income","expense","allocation",perspective==="consumption"?"consumption":"balance","plannedOut"][i])}>{money(v)}</button></td>)}</tr>;
    })}</tbody></table></div></section>
    <div className="dashboard-columns"><section className="panel"><div className="section-heading"><div><h2>분류별 계획과 실제</h2><p>차이 = 계획 − 실제 · 환불은 원거래 분류의 지출에서 차감</p></div><span className="badge">계획 여유자금 {money(planned.remaining)}</span></div><div className="table-scroll"><table className="report-table"><thead><tr><th>유형 · 분류</th><th className="numeric">계획</th><th className="numeric">실제</th><th className="numeric">차이</th></tr></thead><tbody>{categoryRows.map(c=><tr key={c.id}><th>{KINDS[c.kind]} · {c.minor}</th><td className="numeric">{money(c.plan)}</td><td className="numeric"><button className="number-link" onClick={()=>onTransactions(undefined,`category:${c.id}`)}>{money(c.actual)}</button></td><td className={`numeric ${c.plan-c.actual<0?"negative":""}`}>{money(c.plan-c.actual)}</td></tr>)}</tbody></table>{!categoryRows.length&&<p className="empty">계획예산이나 확정 거래를 저장하면 비교할 수 있습니다.</p>}</div></section>
    <section className="panel"><div className="section-heading"><h2>분류별 소비지출</h2></div><div className="bar-chart">{expenseRows.map(c=><div key={c.id}><div className="bar-label"><span>{c.minor}</span><strong>{money(c.actual)}</strong></div><div className="bar-track"><span style={{width:`${c.actual/highest*100}%`}}/></div></div>)}{!expenseRows.length&&<p className="empty">확정된 소비지출이 없습니다.</p>}</div><p className="muted chart-note">예정 거래와 저축·투자·원금상환은 제외했습니다.</p></section></div>
    <section className="panel"><div className="section-heading"><h2>고정비 예정 · 확정 현황</h2><button onClick={()=>onTransactions(undefined,"planned")}>예정 내역 검토·확정</button></div><div className="table-scroll"><table className="report-table"><thead><tr><th>항목</th><th>귀속</th><th>일자</th><th className="numeric">예정금액</th><th className="numeric">현재금액</th><th>상태</th></tr></thead><tbody>{data.transactions.filter(t=>t.recurrence_rule_id).map(t=><tr key={t.id}><th>{t.description}</th><td>{t.owner}</td><td>{t.date}</td><td className="numeric">{money(t.planned_amount??t.amount)}</td><td className="numeric">{money(t.amount)}</td><td><span className={`badge ${t.status==="planned"?"warning":""}`}>{t.status==="planned"?"◷ 예정":t.status==="confirmed"?"✓ 확정":"− 취소"}</span></td></tr>)}</tbody></table>{!data.transactions.some(t=>t.recurrence_rule_id)&&<p className="empty">고정비 메뉴에서 반복 항목을 등록하면 해당 월에 예정 거래가 생성됩니다.</p>}</div></section>
    <BudgetEditor data={data} month={month} onDirty={onDirty} onSaved={onSaved}/>
    <section className="panel"><div className="section-heading"><h2>최근 거래내역</h2><button onClick={()=>onTransactions()}>전체 내역 조회·입력</button></div><div className="table-scroll"><table className="report-table"><thead><tr><th>날짜</th><th>귀속</th><th>내용</th><th>유형</th><th className="numeric">금액</th><th>상태</th></tr></thead><tbody>{[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(t=><tr key={t.id}><td>{t.date}</td><td>{t.owner}</td><th>{t.description}</th><td>{KINDS[t.kind]}</td><td className="numeric">{money(t.amount)}</td><td>{t.status==="confirmed"?"✓ 확정":t.status==="planned"?"◷ 예정":"− 취소"}</td></tr>)}</tbody></table>{!data.transactions.length&&<p className="empty">저장된 거래가 없습니다.</p>}</div></section>
    </>}
  </>;
}
