"use client";
import { useEffect, useRef, useState } from "react";
import { OWNERS,KINDS,koreaDate,money,type LedgerData,type RecurringRule,type Owner,type Kind } from "@/lib/domain";
import { postJson } from "@/lib/http";
type Form = Omit<RecurringRule,"id"|"rule_id"|"amount"> & {id?:string;rule_id?:string;amount:string};
export default function RecurringEditor({data,month,onSaved,onDirty}:{data:LedgerData;month:string;onSaved:()=>Promise<void>;onDirty:(scope:string,dirty:boolean)=>void}) {
  const initial:Form={effective_month:month<koreaDate().slice(0,7)?koreaDate().slice(0,7):month,name:"",owner:"기타",kind:"expense",category_id:data.categories.find(c=>c.kind==="expense")?.id??"",amount:"",payment_method_id:null,account_id:null,interval_months:1,day:1,start_month:month,end_month:null,enabled:true};
  const [form,setForm]=useState<Form>(initial),[baseline,setBaseline]=useState(JSON.stringify(initial)),[saving,setSaving]=useState(false),[message,setMessage]=useState("");const busy=useRef(false);
  const request=useRef<{fingerprint:string;id:string}|null>(null);
  const dirty=JSON.stringify(form)!==baseline;
  useEffect(()=>{onDirty("recurring",dirty);return()=>onDirty("recurring",false);},[dirty,onDirty]);
  useEffect(()=>{onDirty("busy:recurring",saving);return()=>onDirty("busy:recurring",false);},[saving,onDirty]);
  const update=(patch:Partial<Form>)=>{setForm(current=>({...current,...patch}));setMessage("");};
  const edit=(r:RecurringRule)=>{const next={...r,amount:String(r.amount),effective_month:month<koreaDate().slice(0,7)?koreaDate().slice(0,7):month};if(dirty&&!window.confirm("작성 중인 규칙을 취소하고 선택한 항목을 수정할까요?"))return;setForm(next);setBaseline(JSON.stringify(next));setMessage("");};
  const save=async()=>{if(busy.current)return;const fingerprint=JSON.stringify(form);if(request.current?.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};busy.current=true;setSaving(true);let committed=false;try{await postJson("/api/recurring",{request_id:request.current!.id,rule:form});committed=true;await onSaved();setMessage("고정비 규칙을 저장했습니다. 선택한 월의 예정 내역을 갱신했습니다. 확정·수정·건너뛴 내역은 보존됩니다.");setForm(initial);setBaseline(JSON.stringify(initial));request.current=null;}catch(e){setMessage(committed?"규칙 저장은 완료됐지만 조회에 실패했습니다. 같은 내용으로 재시도하면 중복 없이 조회합니다.":(e as Error).message);}finally{busy.current=false;setSaving(false);}};
  return <><section className="panel"><div className="section-heading"><div><h2>고정비 · 반복거래</h2><p>해당 월을 열 때 예정 상태로 생성합니다. 원장 표에서 실제 금액을 입력하고 확정하세요.</p></div></div><div className="table-scroll"><table className="report-table"><thead><tr><th>항목</th><th>귀속</th><th>유형·분류</th><th className="numeric">예정금액</th><th>반복·예정일</th><th>시작·종료</th><th>적용 시작월</th><th>사용</th><th>작업</th></tr></thead><tbody>{data.rules.map(r=><tr key={r.rule_id}><th>{r.name}</th><td>{r.owner}</td><td>{KINDS[r.kind]} · {data.categories.find(c=>c.id===r.category_id)?.minor}</td><td className="numeric">{money(r.amount)}</td><td>{r.interval_months}개월마다 · {r.day}일</td><td>{r.start_month} ~ {r.end_month??"종료 없음"}</td><td>{r.effective_month}</td><td>{r.enabled?"사용":"중지"}</td><td><button disabled={saving} onClick={()=>edit(r)}>변경 예약</button></td></tr>)}</tbody></table>{!data.rules.length&&<p className="empty">반복 항목을 등록하세요. 매월 31일은 해당 월의 말일로 처리합니다.</p>}</div></section>
    <section className="panel"><div className="section-heading"><div><h2>{form.rule_id?"반복규칙 변경":"반복 항목 등록"}</h2><p>과거 확정 거래와 계획을 덮어쓰지 않습니다. 특정 월을 건너뛰려면 원장의 해당 예정 거래를 취소하세요.</p></div></div><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset className="form-grid" disabled={saving}>
      <label>항목명<input required maxLength={120} value={form.name} onChange={e=>update({name:e.target.value})}/></label><label>귀속<select value={form.owner} onChange={e=>update({owner:e.target.value as Owner})}>{OWNERS.map(o=><option key={o}>{o}</option>)}</select></label>
      <label>거래유형<select value={form.kind} onChange={e=>update({kind:e.target.value as Kind,category_id:data.categories.find(c=>c.kind===e.target.value)?.id??""})}>{["income","expense","saving","loan_principal"].map(k=><option key={k} value={k}>{KINDS[k as Kind]}</option>)}</select></label><label>분류<select required value={form.category_id} onChange={e=>update({category_id:e.target.value})}>{data.categories.filter(c=>c.kind===form.kind).map(c=><option key={c.id} value={c.id}>{c.major} / {c.minor}</option>)}</select></label>
      <label>예정금액<input required inputMode="numeric" value={form.amount} onChange={e=>update({amount:e.target.value})} placeholder="12,300"/></label><label>결제수단<select value={form.payment_method_id??""} onChange={e=>update({payment_method_id:e.target.value||null})}><option value="">선택 안 함</option>{data.methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>계좌·카드<select value={form.account_id??""} onChange={e=>update({account_id:e.target.value||null})}><option value="">선택 안 함</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
      <label>반복주기<select value={form.interval_months} onChange={e=>update({interval_months:Number(e.target.value)})}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1}개월</option>)}</select></label><label>예정일<input type="number" required min={1} max={31} value={form.day} onChange={e=>update({day:Number(e.target.value)})}/></label><label>시작월<input type="month" required value={form.start_month} onChange={e=>update({start_month:e.target.value})}/></label><label>종료월<input type="month" value={form.end_month??""} onChange={e=>update({end_month:e.target.value||null})}/></label><label>변경 적용 시작월<input type="month" required value={form.effective_month} min={form.rule_id?koreaDate().slice(0,7):undefined} onChange={e=>update({effective_month:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={form.enabled} onChange={e=>update({enabled:e.target.checked})}/> 규칙 사용</label>
      <div className="form-actions"><button type="submit" className="primary" disabled={saving}>{saving?"저장 중…":form.rule_id?"변경 예약 저장":"반복 항목 저장"}</button><button type="button" disabled={saving} onClick={()=>{if(!dirty||window.confirm("작성 중인 규칙을 취소할까요?")){setForm(initial);setBaseline(JSON.stringify(initial));setMessage("");}}}>작성 취소</button></div>
    </fieldset></form>{message&&<p className="notice" role="status">{message}</p>}</section></>;
}
