"use client";
import { useEffect,useRef,useState } from "react";
import { KINDS,type LedgerData } from "@/lib/domain";
import { postJson } from "@/lib/http";
export default function Settings({data,onSaved,onDirty}:{data:LedgerData;onSaved:()=>Promise<void>;onDirty:(scope:string,dirty:boolean)=>void}){
  const [type,setType]=useState("account"),[name,setName]=useState(""),[kind,setKind]=useState("bank"),[major,setMajor]=useState(""),[minor,setMinor]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  const request=useRef<{fingerprint:string;id:string}|null>(null);
  const dirty=!!name||!!major||!!minor;useEffect(()=>{onDirty("settings",dirty);return()=>onDirty("settings",false);},[dirty,onDirty]);
  useEffect(()=>{onDirty("busy:settings",saving);return()=>onDirty("busy:settings",false);},[saving,onDirty]);
  const save=async()=>{if(saving)return;setSaving(true);let committed=false;try{const payload={type,item:type==="category"?{kind,major,minor}:{name,kind}};const fingerprint=JSON.stringify(payload);if(request.current?.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};await postJson("/api/settings",{...payload,request_id:request.current!.id});committed=true;await onSaved();setName("");setMajor("");setMinor("");request.current=null;setMessage("설정을 DB에 저장했습니다.");}catch(e){setMessage(committed?"설정 저장은 완료됐지만 조회에 실패했습니다. 같은 내용으로 재시도하세요.":(e as Error).message);}finally{setSaving(false);}};
  return <><section className="panel"><div className="section-heading"><h2>가족 · 연결 정보</h2><span className="badge success">✓ 인증된 DB 연결</span></div><dl className="details"><dt>가족</dt><dd>{data.family.name}</dd><dt>로그인 사용자</dt><dd>{data.member.display_name}</dd><dt>권한</dt><dd>{data.member.role==="owner"?"가족 관리자":"가족 구성원"}</dd><dt>기록 귀속</dt><dd>상화 / 하율 / 기타 — 누가 로그인했는지와 별개</dd><dt>데이터 저장</dt><dd>Supabase 서버 DB · 가족 단위 RLS · 원자적 일괄 저장</dd></dl><p className="muted">가족 계정 승인·초대는 Supabase 관리 화면과 DB 설정으로 진행합니다. 앱에서 누구나 가입할 수 없도록 구성했습니다.</p></section>
    <section className="panel"><div className="section-heading"><h2>계좌·카드 / 결제수단 / 분류 등록</h2></div><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset className="form-grid" disabled={saving}><label>등록 항목<select value={type} onChange={e=>{setType(e.target.value);setKind(e.target.value==="category"?"expense":"bank");}}><option value="account">계좌·카드</option><option value="method">결제수단</option><option value="category">분류</option></select></label>{type!=="category"?<label>명칭<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>:<><label>대분류<input required maxLength={80} value={major} onChange={e=>setMajor(e.target.value)}/></label><label>소분류<input required maxLength={80} value={minor} onChange={e=>setMinor(e.target.value)}/></label></>}{type==="account"&&<label>종류<select value={kind} onChange={e=>setKind(e.target.value)}><option value="bank">은행계좌</option><option value="card">카드</option><option value="asset">저축·투자계좌</option><option value="loan">대출계좌</option></select></label>}{type==="category"&&<label>거래유형<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(KINDS).filter(([k])=>k!=="refund").map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}<div className="form-actions"><button className="primary" disabled={saving}>{saving?"저장 중…":"등록"}</button></div></fieldset></form>{message&&<p className="notice" role="status">{message}</p>}</section>
    <div className="dashboard-columns"><section className="panel"><h2>등록된 계좌·카드</h2>{data.accounts.length?<ul className="reference-list">{data.accounts.map(a=><li key={a.id}>{a.name}<span className="badge">{{bank:"은행",card:"카드",asset:"저축·투자",loan:"대출"}[a.kind]}</span></li>)}</ul>:<p className="empty">사용할 계좌·카드를 먼저 등록하세요.</p>}</section><section className="panel"><h2>결제수단</h2><ul className="reference-list">{data.methods.map(m=><li key={m.id}>{m.name}</li>)}</ul></section></div>
    <section className="panel"><h2>등록된 분류</h2><div className="reference-grid">{data.categories.map(c=><span className="badge" key={c.id}>{KINDS[c.kind]} · {c.major} / {c.minor}</span>)}</div></section>
  </>;
}
